version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}
    container_name: app
    restart: unless-stopped
    ports:
      - "5173:5173"
    tty: true
    volumes:
      - ./src:/var/www/html
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    networks:
      - vorlisnet
  # Nginx Service
  webserver:
    image: nginx:1.25.3-alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - vorlisnet
  db:
    image: postgres:16
    restart: always
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: ${MY_POSTGRES_DB}
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/data
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgresqldata:/var/lib/postgresql/data
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - vorlisnet

#Docker Networks
networks:
  vorlisnet:
    driver: bridge
#Volumes
volumes:
  postgresqldata:
    driver: local